<?php

namespace App\Command;

use App\Entity\Team;
use App\Entity\User;
use App\Entity\TeamMembership;
use App\Enum\AccountStatus;
use App\Enum\TeamStatus;
use App\Enum\TeamRole;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

#[AsCommand(
    name: 'app:seed-data',
    description: 'Seeds the database with 10 users and 4 teams',
)]
class SeedDataCommand extends Command
{
    public function __construct(
        private EntityManagerInterface $entityManager,
        private UserPasswordHasherInterface $passwordHasher
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $users = [];
        for ($i = 1; $i <= 10; ++$i) {
            $user = new User();
            $user->setEmail("user{$i}@carthage-arena.com");
            $user->setUsername("user{$i}");
            $user->setNickname("Player {$i}");
            $user->setRoles(['ROLE_USER']);
            $user->setStatus(AccountStatus::ACTIVE);
            $user->setBalance(100);

            // Hash password
            $hashedPassword = $this->passwordHasher->hashPassword($user, 'password123');
            $user->setPassword($hashedPassword);

            $this->entityManager->persist($user);
            $users[] = $user;
        }

        // Persist users first so we have them available (though Doctrine might handle it in one flush usually, 
        // but let's be safe for ID generation if UUIDs are generated by doctrine)
        // Actually UUIDs are generated by doctrine.uuid_generator. 
        // We can flush once at the end.

        $io->note('Created 10 users.');

        $teamNames = ['Team Alpha', 'Team Beta', 'Team Gamma', 'Team Delta'];
        $teamTags = ['ALPHA', 'BETA', 'GAMMA', 'DELTA'];

        foreach ($teamNames as $index => $name) {
            $team = new Team();
            $team->setName($name);
            $team->setTag($teamTags[$index]);
            $team->setDescription("Description for {$name}");
            $team->setInviteCode(strtoupper(substr(md5(uniqid()), 0, 8))); // basic random code
            $team->setStatus(TeamStatus::ACTIVE);

            // Assign a random captain from the created users
            // user1 -> Team Alpha, user2 -> Team Beta, etc.
            if (isset($users[$index])) {
                $captain = $users[$index];
                $team->setCaptain($captain);
                $this->entityManager->persist($team);

                // Create Captain Membership
                $membership = new TeamMembership();
                $membership->setTeam($team);
                $membership->setPlayer($captain);
                $membership->setRole(TeamRole::CAPTAIN);
                $membership->setJoinedAt(new \DateTimeImmutable());
                $this->entityManager->persist($membership);

                // Add 1 more member to each team from the remaining users (if available)
                // Team 0 uses user 4
                // Team 1 uses user 5
                // Team 2 uses user 6
                // Team 3 uses user 7
                $memberIndex = $index + 4;
                if (isset($users[$memberIndex])) {
                    $memberUser = $users[$memberIndex];
                    $memberShip2 = new TeamMembership();
                    $memberShip2->setTeam($team);
                    $memberShip2->setPlayer($memberUser);
                    $memberShip2->setRole(TeamRole::MEMBER);
                    $memberShip2->setJoinedAt(new \DateTimeImmutable());
                    $this->entityManager->persist($memberShip2);
                }
            }
        }

        $io->note('Created 4 teams with memberships.');

        $this->entityManager->flush();

        $io->success('Database seeded successfully!');

        return Command::SUCCESS;
    }
}
